name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is there an existing request for this feature?
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched the existing issues and this is a new feature request
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Describe alternatives you've considered
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend API
        - Frontend Dashboard
        - Regulatory Monitoring
        - Code Generation
        - GitHub Integration
        - Authentication/SSO
        - Billing
        - CLI
        - Docker/Infrastructure
        - Documentation
        - New Component
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Blocking my use case
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I'd like to implement this myself"
        - "Yes, I could help with implementation"
        - "I could help with testing"
        - "I could help with documentation"
        - "No, I'm just suggesting"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        - Industry/sector:
        - Regulations you work with:
        - Team size:
        - How would this feature help you?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Link to any similar features in other tools, or relevant documentation
      placeholder: |
        - Similar feature in XYZ tool: [link]
        - Relevant documentation: [link]
    validations:
      required: false
