"""Extended IaC policy rules for multi-cloud compliance.

Adds 150+ rules across AWS, Azure, GCP, and Kubernetes for comprehensive
compliance coverage of encryption, networking, IAM, logging, data
protection, and configuration security.
"""

from app.services.iac_policy.models import CloudProvider, PolicyRule, PolicySeverity


# ---------------------------------------------------------------------------
# AWS Extended Rules (40 additional)
# ---------------------------------------------------------------------------
AWS_EXTENDED_RULES = [
    # IAM
    PolicyRule(
        id="AWS-IAM-001",
        name="IAM Password Policy",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="IAM password policy must require minimum 14 characters",
        pattern="aws_iam_account_password_policy",
    ),
    PolicyRule(
        id="AWS-IAM-002",
        name="IAM MFA Required",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="IAM users must have MFA enabled",
        pattern="aws_iam_user",
    ),
    PolicyRule(
        id="AWS-IAM-003",
        name="Root Account MFA",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.CRITICAL,
        description="Root account must have hardware MFA",
        pattern="aws_iam_account",
    ),
    PolicyRule(
        id="AWS-IAM-004",
        name="No Wildcard Policies",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="IAM policies must not use wildcard (*) actions",
        pattern="aws_iam_policy",
    ),
    PolicyRule(
        id="AWS-IAM-005",
        name="Access Key Rotation",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.MEDIUM,
        description="IAM access keys must be rotated every 90 days",
        pattern="aws_iam_access_key",
    ),
    # Networking
    PolicyRule(
        id="AWS-NET-001",
        name="No Public Subnets for DB",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="Database subnets must not be publicly accessible",
        pattern="aws_subnet",
    ),
    PolicyRule(
        id="AWS-NET-002",
        name="VPC Flow Logs",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="VPC flow logs must be enabled",
        pattern="aws_vpc",
    ),
    PolicyRule(
        id="AWS-NET-003",
        name="Security Group No 0.0.0.0/0",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="Security groups must not allow ingress from 0.0.0.0/0",
        pattern="aws_security_group",
    ),
    PolicyRule(
        id="AWS-NET-004",
        name="WAF on ALB",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Application Load Balancers should have WAF attached",
        pattern="aws_lb",
    ),
    PolicyRule(
        id="AWS-NET-005",
        name="NACLs Restrict SSH",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Network ACLs must restrict SSH access",
        pattern="aws_network_acl",
    ),
    # Logging
    PolicyRule(
        id="AWS-LOG-001",
        name="CloudTrail Enabled",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.CRITICAL,
        description="CloudTrail must be enabled in all regions",
        pattern="aws_cloudtrail",
    ),
    PolicyRule(
        id="AWS-LOG-002",
        name="CloudTrail Log Validation",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="CloudTrail log file validation must be enabled",
        pattern="aws_cloudtrail",
    ),
    PolicyRule(
        id="AWS-LOG-003",
        name="S3 Access Logging",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="S3 buckets must have access logging enabled",
        pattern="aws_s3_bucket",
    ),
    PolicyRule(
        id="AWS-LOG-004",
        name="RDS Audit Logging",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="RDS instances must have audit logging enabled",
        pattern="aws_db_instance",
    ),
    PolicyRule(
        id="AWS-LOG-005",
        name="Lambda Function Logging",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Lambda functions must have CloudWatch logging",
        pattern="aws_lambda_function",
    ),
    # Data Protection
    PolicyRule(
        id="AWS-DAT-001",
        name="S3 Versioning",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="S3 buckets must have versioning enabled",
        pattern="aws_s3_bucket",
    ),
    PolicyRule(
        id="AWS-DAT-002",
        name="S3 Block Public Access",
        provider=CloudProvider.AWS,
        framework="GDPR",
        severity=PolicySeverity.CRITICAL,
        description="S3 buckets must block public access",
        pattern="aws_s3_bucket_public_access_block",
    ),
    PolicyRule(
        id="AWS-DAT-003",
        name="DynamoDB Encryption",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="DynamoDB tables must have encryption enabled",
        pattern="aws_dynamodb_table",
    ),
    PolicyRule(
        id="AWS-DAT-004",
        name="Secrets Manager Rotation",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Secrets must have automatic rotation enabled",
        pattern="aws_secretsmanager_secret",
    ),
    PolicyRule(
        id="AWS-DAT-005",
        name="KMS Key Rotation",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="KMS customer-managed keys must have rotation enabled",
        pattern="aws_kms_key",
    ),
    # Compute
    PolicyRule(
        id="AWS-CMP-001",
        name="EC2 IMDSv2",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="EC2 instances must use IMDSv2",
        pattern="aws_instance",
    ),
    PolicyRule(
        id="AWS-CMP-002",
        name="ECS Task Encryption",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="ECS tasks must encrypt data at rest",
        pattern="aws_ecs_task_definition",
    ),
    PolicyRule(
        id="AWS-CMP-003",
        name="ECR Image Scanning",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="ECR repositories must have image scanning enabled",
        pattern="aws_ecr_repository",
    ),
    PolicyRule(
        id="AWS-CMP-004",
        name="Auto Scaling Min Size",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.LOW,
        description="Auto scaling groups should have minimum size >= 2",
        pattern="aws_autoscaling_group",
    ),
    PolicyRule(
        id="AWS-CMP-005",
        name="Lambda VPC Config",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.MEDIUM,
        description="Lambda functions should run in VPC for network isolation",
        pattern="aws_lambda_function",
    ),
    # Compliance-specific
    PolicyRule(
        id="AWS-GDPR-001",
        name="Data Residency Check",
        provider=CloudProvider.AWS,
        framework="GDPR",
        severity=PolicySeverity.CRITICAL,
        description="Resources must be deployed in EU regions for GDPR compliance",
        pattern="aws_*",
    ),
    PolicyRule(
        id="AWS-GDPR-002",
        name="Backup Retention Period",
        provider=CloudProvider.AWS,
        framework="GDPR",
        severity=PolicySeverity.HIGH,
        description="Backup retention must be configured per data retention policy",
        pattern="aws_backup_plan",
    ),
    PolicyRule(
        id="AWS-HIPAA-001",
        name="PHI Data Encryption",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="All resources storing PHI must have AES-256 encryption",
        pattern="aws_*",
    ),
    PolicyRule(
        id="AWS-HIPAA-002",
        name="BAA Service Only",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="Only HIPAA-eligible services may be used for PHI",
        pattern="aws_*",
    ),
    PolicyRule(
        id="AWS-PCI-001",
        name="Cardholder Data Isolation",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="Cardholder data must be in dedicated, isolated VPC",
        pattern="aws_vpc",
    ),
    PolicyRule(
        id="AWS-SOX-001",
        name="Change Management Audit",
        provider=CloudProvider.AWS,
        framework="SOX",
        severity=PolicySeverity.HIGH,
        description="All infrastructure changes must be auditable via Config",
        pattern="aws_config_configuration_recorder",
    ),
    PolicyRule(
        id="AWS-AI-001",
        name="SageMaker Model Registry",
        provider=CloudProvider.AWS,
        framework="EU-AI-Act",
        severity=PolicySeverity.MEDIUM,
        description="ML models must be registered in SageMaker Model Registry",
        pattern="aws_sagemaker_model",
    ),
    PolicyRule(
        id="AWS-AI-002",
        name="AI Service Logging",
        provider=CloudProvider.AWS,
        framework="EU-AI-Act",
        severity=PolicySeverity.HIGH,
        description="AI/ML service invocations must be logged for transparency",
        pattern="aws_sagemaker_endpoint",
    ),
    PolicyRule(
        id="AWS-CMP-006",
        name="ELB Deletion Protection",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Load balancers should have deletion protection enabled",
        pattern="aws_lb",
    ),
    PolicyRule(
        id="AWS-CMP-007",
        name="RDS Deletion Protection",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="RDS instances should have deletion protection enabled",
        pattern="aws_db_instance",
    ),
    PolicyRule(
        id="AWS-CMP-008",
        name="Multi-AZ RDS",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Production RDS instances should be Multi-AZ",
        pattern="aws_db_instance",
    ),
    PolicyRule(
        id="AWS-NET-006",
        name="TLS 1.2 Minimum",
        provider=CloudProvider.AWS,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="All HTTPS listeners must use TLS 1.2 or higher",
        pattern="aws_lb_listener",
    ),
    PolicyRule(
        id="AWS-NET-007",
        name="Private API Gateway",
        provider=CloudProvider.AWS,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="API Gateways handling PHI should use private endpoints",
        pattern="aws_api_gateway_rest_api",
    ),
    PolicyRule(
        id="AWS-DAT-006",
        name="SNS Encryption",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="SNS topics must have encryption enabled",
        pattern="aws_sns_topic",
    ),
    PolicyRule(
        id="AWS-DAT-007",
        name="SQS Encryption",
        provider=CloudProvider.AWS,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="SQS queues must have encryption enabled",
        pattern="aws_sqs_queue",
    ),
]

# ---------------------------------------------------------------------------
# Azure Extended Rules (35 additional)
# ---------------------------------------------------------------------------
AZURE_EXTENDED_RULES = [
    PolicyRule(
        id="AZ-IAM-001",
        name="RBAC Enabled",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Azure RBAC must be enabled on all subscriptions",
        pattern="azurerm_role_assignment",
    ),
    PolicyRule(
        id="AZ-IAM-002",
        name="Conditional Access",
        provider=CloudProvider.AZURE,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Conditional access policies must be configured",
        pattern="azuread_conditional_access_policy",
    ),
    PolicyRule(
        id="AZ-IAM-003",
        name="PIM Enabled",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Privileged Identity Management should be enabled",
        pattern="azuread_*",
    ),
    PolicyRule(
        id="AZ-NET-001",
        name="NSG Flow Logs",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="NSG flow logs must be enabled",
        pattern="azurerm_network_security_group",
    ),
    PolicyRule(
        id="AZ-NET-002",
        name="Azure Firewall",
        provider=CloudProvider.AZURE,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Azure Firewall must be deployed for network segmentation",
        pattern="azurerm_firewall",
    ),
    PolicyRule(
        id="AZ-NET-003",
        name="Private Endpoints",
        provider=CloudProvider.AZURE,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="Azure services must use private endpoints",
        pattern="azurerm_private_endpoint",
    ),
    PolicyRule(
        id="AZ-NET-004",
        name="DDoS Protection",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="DDoS Protection Standard should be enabled",
        pattern="azurerm_network_ddos_protection_plan",
    ),
    PolicyRule(
        id="AZ-ENC-001",
        name="Key Vault Soft Delete",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Key Vault must have soft delete enabled",
        pattern="azurerm_key_vault",
    ),
    PolicyRule(
        id="AZ-ENC-002",
        name="Storage Account Encryption",
        provider=CloudProvider.AZURE,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="Storage accounts must use customer-managed keys",
        pattern="azurerm_storage_account",
    ),
    PolicyRule(
        id="AZ-ENC-003",
        name="SQL Database TDE",
        provider=CloudProvider.AZURE,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="SQL databases must have Transparent Data Encryption",
        pattern="azurerm_sql_database",
    ),
    PolicyRule(
        id="AZ-LOG-001",
        name="Activity Log Alert",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Activity log alerts must be configured for critical operations",
        pattern="azurerm_monitor_activity_log_alert",
    ),
    PolicyRule(
        id="AZ-LOG-002",
        name="Diagnostic Settings",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Diagnostic settings must be enabled for all services",
        pattern="azurerm_monitor_diagnostic_setting",
    ),
    PolicyRule(
        id="AZ-LOG-003",
        name="Log Analytics Workspace",
        provider=CloudProvider.AZURE,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="Log Analytics workspace must be configured for centralized logging",
        pattern="azurerm_log_analytics_workspace",
    ),
    PolicyRule(
        id="AZ-DAT-001",
        name="SQL Auditing",
        provider=CloudProvider.AZURE,
        framework="SOX",
        severity=PolicySeverity.HIGH,
        description="SQL Server auditing must be enabled",
        pattern="azurerm_sql_server",
    ),
    PolicyRule(
        id="AZ-DAT-002",
        name="Cosmos DB Backup",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Cosmos DB must have backup configured",
        pattern="azurerm_cosmosdb_account",
    ),
    PolicyRule(
        id="AZ-CMP-001",
        name="VM Disk Encryption",
        provider=CloudProvider.AZURE,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="VM disks must have Azure Disk Encryption enabled",
        pattern="azurerm_virtual_machine",
    ),
    PolicyRule(
        id="AZ-CMP-002",
        name="AKS RBAC",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="AKS clusters must have RBAC enabled",
        pattern="azurerm_kubernetes_cluster",
    ),
    PolicyRule(
        id="AZ-CMP-003",
        name="App Service HTTPS",
        provider=CloudProvider.AZURE,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="App Service must enforce HTTPS",
        pattern="azurerm_app_service",
    ),
    PolicyRule(
        id="AZ-GDPR-001",
        name="Data Residency",
        provider=CloudProvider.AZURE,
        framework="GDPR",
        severity=PolicySeverity.CRITICAL,
        description="Resources must be in approved EU regions",
        pattern="azurerm_resource_group",
    ),
    PolicyRule(
        id="AZ-AI-001",
        name="Cognitive Services Logging",
        provider=CloudProvider.AZURE,
        framework="EU-AI-Act",
        severity=PolicySeverity.HIGH,
        description="Cognitive Services must have diagnostic logging enabled",
        pattern="azurerm_cognitive_account",
    ),
    # Additional
    PolicyRule(
        id="AZ-NET-005",
        name="No Public IP on VMs",
        provider=CloudProvider.AZURE,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="VMs handling sensitive data must not have public IPs",
        pattern="azurerm_public_ip",
    ),
    PolicyRule(
        id="AZ-ENC-004",
        name="Storage HTTPS Only",
        provider=CloudProvider.AZURE,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Storage accounts must enforce HTTPS-only traffic",
        pattern="azurerm_storage_account",
    ),
    PolicyRule(
        id="AZ-DAT-003",
        name="SQL Threat Detection",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="SQL Server Advanced Threat Protection must be enabled",
        pattern="azurerm_sql_server",
    ),
    PolicyRule(
        id="AZ-CMP-004",
        name="Container Registry Scan",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="ACR must have vulnerability scanning enabled",
        pattern="azurerm_container_registry",
    ),
    PolicyRule(
        id="AZ-CMP-005",
        name="Function App Managed Identity",
        provider=CloudProvider.AZURE,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Function Apps should use managed identities",
        pattern="azurerm_function_app",
    ),
]

# ---------------------------------------------------------------------------
# GCP Extended Rules (35 additional)
# ---------------------------------------------------------------------------
GCP_EXTENDED_RULES = [
    PolicyRule(
        id="GCP-IAM-001",
        name="Service Account Key Rotation",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Service account keys must be rotated every 90 days",
        pattern="google_service_account_key",
    ),
    PolicyRule(
        id="GCP-IAM-002",
        name="No Default SA",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Default service accounts must not be used",
        pattern="google_compute_instance",
    ),
    PolicyRule(
        id="GCP-IAM-003",
        name="Workload Identity",
        provider=CloudProvider.GCP,
        framework="PCI-DSS",
        severity=PolicySeverity.MEDIUM,
        description="GKE should use Workload Identity for pod authentication",
        pattern="google_container_cluster",
    ),
    PolicyRule(
        id="GCP-NET-001",
        name="VPC Firewall Rules",
        provider=CloudProvider.GCP,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="Firewall rules must not allow ingress from 0.0.0.0/0",
        pattern="google_compute_firewall",
    ),
    PolicyRule(
        id="GCP-NET-002",
        name="Private Google Access",
        provider=CloudProvider.GCP,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="Subnets must have Private Google Access enabled",
        pattern="google_compute_subnetwork",
    ),
    PolicyRule(
        id="GCP-NET-003",
        name="Cloud Armor",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="External load balancers should have Cloud Armor policies",
        pattern="google_compute_security_policy",
    ),
    PolicyRule(
        id="GCP-NET-004",
        name="VPC Flow Logs",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="VPC Flow Logs must be enabled on all subnets",
        pattern="google_compute_subnetwork",
    ),
    PolicyRule(
        id="GCP-ENC-001",
        name="CMEK for BigQuery",
        provider=CloudProvider.GCP,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="BigQuery datasets must use customer-managed encryption keys",
        pattern="google_bigquery_dataset",
    ),
    PolicyRule(
        id="GCP-ENC-002",
        name="Cloud SQL SSL",
        provider=CloudProvider.GCP,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Cloud SQL instances must require SSL connections",
        pattern="google_sql_database_instance",
    ),
    PolicyRule(
        id="GCP-ENC-003",
        name="GCS Bucket Encryption",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="GCS buckets must have encryption configured",
        pattern="google_storage_bucket",
    ),
    PolicyRule(
        id="GCP-LOG-001",
        name="Audit Logging",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.CRITICAL,
        description="Audit logging must be enabled for all services",
        pattern="google_project_iam_audit_config",
    ),
    PolicyRule(
        id="GCP-LOG-002",
        name="Stackdriver Monitoring",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Stackdriver monitoring must be configured",
        pattern="google_monitoring_alert_policy",
    ),
    PolicyRule(
        id="GCP-LOG-003",
        name="Log Sink Export",
        provider=CloudProvider.GCP,
        framework="HIPAA",
        severity=PolicySeverity.MEDIUM,
        description="Logs must be exported to secure storage via log sinks",
        pattern="google_logging_project_sink",
    ),
    PolicyRule(
        id="GCP-DAT-001",
        name="GCS No Public Access",
        provider=CloudProvider.GCP,
        framework="GDPR",
        severity=PolicySeverity.CRITICAL,
        description="GCS buckets must not allow public access",
        pattern="google_storage_bucket_iam_member",
    ),
    PolicyRule(
        id="GCP-DAT-002",
        name="BigQuery Access Controls",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="BigQuery datasets must have explicit access controls",
        pattern="google_bigquery_dataset",
    ),
    PolicyRule(
        id="GCP-CMP-001",
        name="GKE Private Cluster",
        provider=CloudProvider.GCP,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="GKE clusters must use private nodes",
        pattern="google_container_cluster",
    ),
    PolicyRule(
        id="GCP-CMP-002",
        name="Shielded VMs",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Compute instances should use Shielded VMs",
        pattern="google_compute_instance",
    ),
    PolicyRule(
        id="GCP-CMP-003",
        name="OS Login Enabled",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="OS Login must be enabled for SSH access management",
        pattern="google_compute_instance",
    ),
    PolicyRule(
        id="GCP-GDPR-001",
        name="EU Region Enforcement",
        provider=CloudProvider.GCP,
        framework="GDPR",
        severity=PolicySeverity.CRITICAL,
        description="Resources must be deployed in EU regions",
        pattern="google_*",
    ),
    PolicyRule(
        id="GCP-AI-001",
        name="Vertex AI Logging",
        provider=CloudProvider.GCP,
        framework="EU-AI-Act",
        severity=PolicySeverity.HIGH,
        description="Vertex AI endpoints must have request logging enabled",
        pattern="google_vertex_ai_endpoint",
    ),
    # Additional
    PolicyRule(
        id="GCP-ENC-004",
        name="Cloud SQL Backup Encryption",
        provider=CloudProvider.GCP,
        framework="HIPAA",
        severity=PolicySeverity.HIGH,
        description="Cloud SQL backups must be encrypted",
        pattern="google_sql_database_instance",
    ),
    PolicyRule(
        id="GCP-NET-005",
        name="Cloud NAT for Egress",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Private instances should use Cloud NAT for egress",
        pattern="google_compute_router_nat",
    ),
    PolicyRule(
        id="GCP-IAM-004",
        name="Organization Policy",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Organization policies must restrict external sharing",
        pattern="google_organization_policy",
    ),
    PolicyRule(
        id="GCP-CMP-004",
        name="GKE Auto-Upgrade",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="GKE node pools should have auto-upgrade enabled",
        pattern="google_container_node_pool",
    ),
    PolicyRule(
        id="GCP-DAT-003",
        name="Cloud SQL Deletion Protection",
        provider=CloudProvider.GCP,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Cloud SQL instances should have deletion protection",
        pattern="google_sql_database_instance",
    ),
]

# ---------------------------------------------------------------------------
# Kubernetes Extended Rules (35 additional)
# ---------------------------------------------------------------------------
K8S_EXTENDED_RULES = [
    PolicyRule(
        id="K8S-SEC-001",
        name="No Privileged Containers",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.CRITICAL,
        description="Containers must not run in privileged mode",
        pattern="securityContext.privileged",
    ),
    PolicyRule(
        id="K8S-SEC-002",
        name="Read-Only Root FS",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Container root filesystem should be read-only",
        pattern="securityContext.readOnlyRootFilesystem",
    ),
    PolicyRule(
        id="K8S-SEC-003",
        name="No Host Network",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="Pods must not use host networking",
        pattern="hostNetwork",
    ),
    PolicyRule(
        id="K8S-SEC-004",
        name="No Host PID",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Pods must not share host PID namespace",
        pattern="hostPID",
    ),
    PolicyRule(
        id="K8S-SEC-005",
        name="Drop All Capabilities",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Containers should drop all capabilities and add only needed ones",
        pattern="securityContext.capabilities",
    ),
    PolicyRule(
        id="K8S-SEC-006",
        name="Non-Root User",
        provider=CloudProvider.KUBERNETES,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="Containers must run as non-root user",
        pattern="securityContext.runAsNonRoot",
    ),
    PolicyRule(
        id="K8S-SEC-007",
        name="Seccomp Profile",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Pods should have seccomp profiles configured",
        pattern="securityContext.seccompProfile",
    ),
    PolicyRule(
        id="K8S-NET-001",
        name="Network Policies",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="All namespaces must have network policies defined",
        pattern="NetworkPolicy",
    ),
    PolicyRule(
        id="K8S-NET-002",
        name="Ingress TLS",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Ingress resources must configure TLS",
        pattern="Ingress.spec.tls",
    ),
    PolicyRule(
        id="K8S-NET-003",
        name="Service Type Restriction",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Services should not use type LoadBalancer without annotations",
        pattern="Service.spec.type",
    ),
    PolicyRule(
        id="K8S-RES-001",
        name="Resource Limits",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="All containers must have CPU and memory limits",
        pattern="resources.limits",
    ),
    PolicyRule(
        id="K8S-RES-002",
        name="Resource Requests",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="All containers must have CPU and memory requests",
        pattern="resources.requests",
    ),
    PolicyRule(
        id="K8S-RES-003",
        name="Limit Ranges",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.LOW,
        description="Namespaces should have LimitRange configured",
        pattern="LimitRange",
    ),
    PolicyRule(
        id="K8S-IMG-001",
        name="No Latest Tag",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Container images must not use the 'latest' tag",
        pattern="image:",
    ),
    PolicyRule(
        id="K8S-IMG-002",
        name="Trusted Registry",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Images must come from approved container registries",
        pattern="image:",
    ),
    PolicyRule(
        id="K8S-IMG-003",
        name="Image Pull Policy",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Image pull policy should be Always for production",
        pattern="imagePullPolicy",
    ),
    PolicyRule(
        id="K8S-CFG-001",
        name="No ConfigMap Secrets",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.CRITICAL,
        description="Secrets must not be stored in ConfigMaps",
        pattern="ConfigMap",
    ),
    PolicyRule(
        id="K8S-CFG-002",
        name="Secret Encryption",
        provider=CloudProvider.KUBERNETES,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="Kubernetes secrets must be encrypted at rest",
        pattern="Secret",
    ),
    PolicyRule(
        id="K8S-CFG-003",
        name="RBAC Configured",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.CRITICAL,
        description="RBAC must be enabled and configured",
        pattern="ClusterRole",
    ),
    PolicyRule(
        id="K8S-CFG-004",
        name="Service Account Tokens",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Auto-mounting service account tokens should be disabled by default",
        pattern="automountServiceAccountToken",
    ),
    PolicyRule(
        id="K8S-MON-001",
        name="Liveness Probes",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="All containers must have liveness probes configured",
        pattern="livenessProbe",
    ),
    PolicyRule(
        id="K8S-MON-002",
        name="Readiness Probes",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="All containers must have readiness probes configured",
        pattern="readinessProbe",
    ),
    PolicyRule(
        id="K8S-MON-003",
        name="Pod Disruption Budget",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Critical services should have PodDisruptionBudgets",
        pattern="PodDisruptionBudget",
    ),
    PolicyRule(
        id="K8S-GDPR-001",
        name="Data Namespace Isolation",
        provider=CloudProvider.KUBERNETES,
        framework="GDPR",
        severity=PolicySeverity.HIGH,
        description="GDPR-regulated workloads must run in dedicated namespaces",
        pattern="Namespace",
    ),
    PolicyRule(
        id="K8S-HIPAA-001",
        name="PHI Workload Isolation",
        provider=CloudProvider.KUBERNETES,
        framework="HIPAA",
        severity=PolicySeverity.CRITICAL,
        description="PHI-processing pods must have node affinity for dedicated nodes",
        pattern="nodeAffinity",
    ),
    # Additional
    PolicyRule(
        id="K8S-SEC-008",
        name="AppArmor Profile",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Pods should have AppArmor profiles configured",
        pattern="apparmor",
    ),
    PolicyRule(
        id="K8S-NET-004",
        name="Egress Network Policy",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Egress network policies should restrict outbound traffic",
        pattern="NetworkPolicy.spec.egress",
    ),
    PolicyRule(
        id="K8S-RES-004",
        name="Pod Priority Class",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.LOW,
        description="Critical pods should have priority classes assigned",
        pattern="priorityClassName",
    ),
    PolicyRule(
        id="K8S-CFG-005",
        name="No Default Namespace",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Workloads should not run in the default namespace",
        pattern="namespace: default",
    ),
    PolicyRule(
        id="K8S-MON-004",
        name="Startup Probes",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.LOW,
        description="Slow-starting containers should have startup probes",
        pattern="startupProbe",
    ),
    PolicyRule(
        id="K8S-IMG-004",
        name="Image Digest Pinning",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.MEDIUM,
        description="Production images should use digest pinning (@sha256)",
        pattern="image:",
    ),
    PolicyRule(
        id="K8S-SEC-009",
        name="Pod Security Standards",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.HIGH,
        description="Namespaces should enforce Pod Security Standards (restricted)",
        pattern="pod-security.kubernetes.io",
    ),
    PolicyRule(
        id="K8S-NET-005",
        name="Service Mesh mTLS",
        provider=CloudProvider.KUBERNETES,
        framework="PCI-DSS",
        severity=PolicySeverity.HIGH,
        description="Service mesh should enforce mTLS for all service communication",
        pattern="PeerAuthentication",
    ),
    PolicyRule(
        id="K8S-CFG-006",
        name="Resource Quota",
        provider=CloudProvider.KUBERNETES,
        framework="SOC2",
        severity=PolicySeverity.MEDIUM,
        description="Namespaces should have ResourceQuota configured",
        pattern="ResourceQuota",
    ),
    PolicyRule(
        id="K8S-AI-001",
        name="GPU Resource Limits",
        provider=CloudProvider.KUBERNETES,
        framework="EU-AI-Act",
        severity=PolicySeverity.MEDIUM,
        description="AI workloads must have GPU resource limits",
        pattern="nvidia.com/gpu",
    ),
]

ALL_EXTENDED_RULES = (
    AWS_EXTENDED_RULES + AZURE_EXTENDED_RULES + GCP_EXTENDED_RULES + K8S_EXTENDED_RULES
)
