"""Hybrid re-ranking and query expansion for RAG v2.

Combines keyword (BM25/Elasticsearch) and semantic (pgvector) scores using
reciprocal rank fusion, and expands queries with regulation-specific synonyms.
"""

from dataclasses import dataclass, field
from typing import Any

import structlog

from app.services.chat.rag import RAGDocument


logger = structlog.get_logger()

# Regulation synonyms for query expansion
REGULATION_SYNONYMS: dict[str, list[str]] = {
    "gdpr": [
        "general data protection regulation",
        "data protection",
        "privacy",
        "eu privacy",
        "dpa",
    ],
    "ccpa": ["california consumer privacy act", "cpra", "california privacy"],
    "hipaa": [
        "health insurance portability",
        "phi",
        "protected health information",
        "healthcare privacy",
    ],
    "pci-dss": ["pci dss", "payment card industry", "cardholder data", "card security"],
    "eu ai act": ["artificial intelligence act", "ai regulation", "ai act", "ai compliance"],
    "sox": ["sarbanes-oxley", "financial reporting", "internal controls"],
    "soc 2": ["soc2", "service organization control", "trust services criteria"],
    "iso 27001": ["iso27001", "information security management", "isms"],
    "nis2": ["network and information security", "nis directive"],
    "dora": ["digital operational resilience", "financial resilience"],
}


@dataclass
class RankedDocument:
    """A document with combined ranking scores."""

    document: RAGDocument
    keyword_rank: int | None = None
    vector_rank: int | None = None
    fused_score: float = 0.0


def reciprocal_rank_fusion(
    keyword_results: list[RAGDocument],
    vector_results: list[RAGDocument],
    k: int = 60,
    keyword_weight: float = 0.4,
    vector_weight: float = 0.6,
) -> list[RAGDocument]:
    """Merge keyword and vector search results using weighted reciprocal rank fusion.

    RRF formula: score(d) = Σ  weight / (k + rank(d))
    where k is a constant (default 60) to prevent high-ranking items
    from dominating.
    """
    scores: dict[str, RankedDocument] = {}

    for rank, doc in enumerate(keyword_results):
        if doc.id not in scores:
            scores[doc.id] = RankedDocument(document=doc)
        scores[doc.id].keyword_rank = rank
        scores[doc.id].fused_score += keyword_weight / (k + rank)

    for rank, doc in enumerate(vector_results):
        if doc.id not in scores:
            scores[doc.id] = RankedDocument(document=doc)
        scores[doc.id].vector_rank = rank
        scores[doc.id].fused_score += vector_weight / (k + rank)

    ranked = sorted(scores.values(), key=lambda r: r.fused_score, reverse=True)

    for item in ranked:
        item.document.relevance_score = item.fused_score

    logger.debug(
        "RRF merge completed",
        keyword_count=len(keyword_results),
        vector_count=len(vector_results),
        merged_count=len(ranked),
    )

    return [r.document for r in ranked]


def expand_query(query: str) -> str:
    """Expand a query with regulation-specific synonyms for better recall."""
    query_lower = query.lower()
    expansions: list[str] = []

    for key, synonyms in REGULATION_SYNONYMS.items():
        if key in query_lower:
            # Add up to 2 synonyms that aren't already in the query
            added = 0
            for syn in synonyms:
                if syn not in query_lower and added < 2:
                    expansions.append(syn)
                    added += 1

    if expansions:
        expanded = f"{query} ({' '.join(expansions)})"
        logger.debug("Query expanded", original=query[:80], expansions=expansions)
        return expanded
    return query


@dataclass
class GuardrailResult:
    """Result of applying guardrails to a response."""

    content: str
    disclaimers_added: list[str] = field(default_factory=list)
    blocked: bool = False
    block_reason: str | None = None


LEGAL_DISCLAIMER = (
    "\n\n---\n*⚠️ This response is generated by AI and should not be considered legal advice. "
    "Always consult qualified legal counsel for regulatory compliance decisions.*"
)

BLOCKED_PATTERNS = [
    "i am a lawyer",
    "this constitutes legal advice",
    "you are legally required to",
    "i guarantee compliance",
]


def apply_guardrails(
    content: str,
    add_disclaimer: bool = True,
    check_blocked_patterns: bool = True,
) -> GuardrailResult:
    """Apply safety guardrails to assistant responses.

    - Injects legal disclaimers for regulatory content
    - Blocks responses that overstate legal authority
    - Detects and flags potentially misleading claims
    """
    result = GuardrailResult(content=content)

    if check_blocked_patterns:
        content_lower = content.lower()
        for pattern in BLOCKED_PATTERNS:
            if pattern in content_lower:
                result.content = (
                    "I can provide compliance guidance based on regulatory frameworks, "
                    "but I cannot provide legal advice. Please consult a qualified "
                    "legal professional for definitive compliance determinations."
                )
                result.blocked = True
                result.block_reason = f"Blocked pattern detected: {pattern}"
                logger.warning("Guardrail blocked response", reason=result.block_reason)
                return result

    if add_disclaimer:
        # Only add disclaimer if response discusses regulations
        regulatory_terms = ["gdpr", "hipaa", "pci", "sox", "regulation", "compliance", "article"]
        if any(term in content.lower() for term in regulatory_terms):
            result.content += LEGAL_DISCLAIMER
            result.disclaimers_added.append("legal_disclaimer")

    return result


def summarize_conversation_context(
    messages: list[dict[str, Any]],
    max_messages: int = 20,
    max_chars: int = 4000,
) -> str:
    """Summarize older conversation messages to stay within token budget.

    Keeps the most recent ``max_messages`` in full, and summarizes
    older messages into a compact context block.
    """
    if len(messages) <= max_messages:
        return ""

    old_messages = messages[:-max_messages]
    topics: list[str] = []
    regulations_mentioned: set[str] = set()
    files_mentioned: set[str] = set()

    for msg in old_messages:
        content = msg.get("content", "")
        content_lower = content.lower()

        for reg_key in REGULATION_SYNONYMS:
            if reg_key in content_lower:
                regulations_mentioned.add(reg_key.upper())

        import re

        file_pattern = r"[\w/\\.-]+\.(py|js|ts|java|go|rb|php|cs)"
        for match in re.finditer(file_pattern, content):
            files_mentioned.add(match.group(0))

        if msg.get("role") == "user" and len(content) > 10:
            topics.append(content[:120])

    parts = ["[Earlier conversation summary]"]
    if regulations_mentioned:
        parts.append(f"Regulations discussed: {', '.join(sorted(regulations_mentioned))}")
    if files_mentioned:
        parts.append(f"Files referenced: {', '.join(sorted(files_mentioned)[:10])}")
    if topics:
        parts.append("User topics: " + "; ".join(topics[:5]))

    summary = "\n".join(parts)
    return summary[:max_chars]
